// 数据库特定的 SQL 语法指南
const MYSQL_SYNTAX = `
- 使用 MySQL 语法
- 自增主键使用 AUTO_INCREMENT
- 字符串类型使用 VARCHAR(n)，大文本使用 TEXT
- 日期时间使用 DATETIME、TIMESTAMP
- 注释使用 COMMENT 关键字
- 引擎推荐使用 InnoDB: ENGINE=InnoDB
- 字符集推荐 utf8mb4: DEFAULT CHARSET=utf8mb4
- 示例: CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL COMMENT '用户名') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';
`

export const DATABASE_SYNTAX: Record<string, string> = {
  mysql: MYSQL_SYNTAX,
  postgresql: `
- 使用 PostgreSQL 语法
- 自增主键使用 SERIAL 或 BIGSERIAL
- 字符串类型使用 VARCHAR(n)，大文本使用 TEXT
- 日期时间使用 TIMESTAMP、TIMESTAMPTZ
- 注释使用 COMMENT ON 语句
- 支持 UUID 类型
- 示例: CREATE TABLE users (id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL);
COMMENT ON TABLE users IS '用户表';
COMMENT ON COLUMN users.name IS '用户名';
`,
  sqlite: `
- 使用 SQLite 语法
- 自增主键使用 INTEGER PRIMARY KEY AUTOINCREMENT
- 字符串类型使用 TEXT（无长度限制）
- 日期时间使用 TEXT 或 DATETIME
- SQLite 不支持 COMMENT 关键字，字段注释放在字段名后用 -- 注释
- 数据类型简化: INTEGER、TEXT、REAL、BLOB
- 示例: CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL -- 用户名);
`,
  sqlserver: `
- 使用 SQL Server (T-SQL) 语法
- 自增主键使用 IDENTITY(1,1)
- 字符串类型使用 NVARCHAR(n)，大文本使用 NVARCHAR(MAX)
- 日期时间使用 DATETIME、DATETIME2
- 注释使用 EXEC sp_addextendedproperty 存储过程
- 支持 UNIQUEIDENTIFIER 类型 (GUID)
- 示例: CREATE TABLE users (id INT IDENTITY(1,1) PRIMARY KEY, name NVARCHAR(100) NOT NULL);
EXEC sp_addextendedproperty 'MS_Description', '用户表', 'SCHEMA', 'dbo', 'TABLE', 'users';
`,
  oracle: `
- 使用 Oracle 语法
- 自增主键使用序列 (SEQUENCE) + 触发器 (TRIGGER) 或 IDENTITY 列 (12c+)
- 字符串类型使用 VARCHAR2(n)，大文本使用 CLOB
- 日期时间使用 DATE、TIMESTAMP
- 注释使用 COMMENT ON 语句
- 表名、字段名推荐使用大写
- 示例: CREATE TABLE USERS (ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, NAME VARCHAR2(100) NOT NULL);
COMMENT ON TABLE USERS IS '用户表';
`,
  mariadb: `
- 使用 MariaDB 语法（与 MySQL 高度兼容，但部分高级函数有差异）
` + MYSQL_SYNTAX.trim(),
  clickhouse: `
- 使用 ClickHouse 语法
- 主键使用 PRIMARY KEY，排序使用 ORDER BY
- 字符串类型使用 String
- 日期时间使用 DateTime、Date
- 注释使用 COMMENT 关键字
- 必须指定 Engine，常用 MergeTree 系列
- 示例: CREATE TABLE users (id UInt64, name String NOT NULL COMMENT '用户名', created_at DateTime DEFAULT now()) ENGINE = MergeTree() ORDER BY id COMMENT '用户表';
`
}

// Stage 1: Requirement Optimization
export function getRequirementOptimizationPrompt(): string {
  return `你是一个资深业务分析师。
你的任务是对用户原始需求做"需求提炼"，目标只有四个：

1) 提取关键信息：保留可用于数据库建模的业务实体、关系、约束、状态、流程与规则。
2) 精炼需求表达：将口语化、重复或松散描述整理为清晰、紧凑、可执行的业务需求文本。
3) 合并同源异构需求：当多个描述指向同一组核心数据/业务对象，仅因展示形式、入口渠道、交互方式或终端设备不同而产生差异时，必须抽象为一条通用需求，用"支持多端/多形式展示"等表述统一覆盖，避免按表现形式拆分成多条重复需求。
   - 判断标准：若底层字段、业务规则、状态流转一致，仅前端呈现（如列表/卡片/图表）、访问入口（如APP/小程序/H5）、交互细节（如弹窗/抽屉/新页面）不同，则视为同一需求。
   - 示例：「用户信息在APP端以卡片展示，在Web端以表格展示」→ 提炼为「用户信息支持多端自适应展示，核心字段与更新规则统一」。
4) 剔除无效干扰：删除与建模无关内容，如 UI 设计细节、页面样式、交互动效、营销文案、泛化口号、技术实现噪声等。

输出要求：
- 只输出最终的"提炼后需求文本"。
- 使用中文，分段清晰，语义准确。
- 不要输出 JSON，不要输出 markdown 代码块，不要解释你的处理过程。`
}

// Stage 2: Requirement Analysis
export function getAnalysisPrompt(): string {
  return `你是一个资深的业务分析师。
请分析用户的产品需求描述，提取出核心功能关键点。
关键点必须是可映射为数据库建模的内容，禁止输出 UI、样式、页面交互等无关信息。

【极度重要 - JSON 格式要求】：
1. 你必须且只能返回一个合法的 JSON 对象
2. 不要输出任何解释性文字、markdown 标记或代码块
3. 确保 JSON 格式完整，所有括号、引号、逗号都正确闭合
4. 不要在 JSON 中使用中文标点符号（如：，、：等）
5. 字符串值中如果包含引号，请使用转义符 \\"

返回格式示例：
{"keyPoints":["关键点1","关键点2","关键点3"]}

请严格按照上述格式返回结果。`
}

// Stage 3: Schema Design
export function getSchemaDesignPrompt(databaseType: string, keyPoints: string[]): string {
  return `你是一个资深的数据库架构师。
基于以下业务关键点，设计合理的数据库表结构和关系。

业务关键点：
${keyPoints.map(p => `- ${p}`).join('\n')}

【极度重要 - JSON 格式要求】：
1. 你必须且只能返回一个合法的 JSON 对象
2. 不要输出任何解释性文字、markdown 标记或代码块
3. 确保 JSON 格式完整，所有括号、引号、逗号都正确闭合
4. 不要在 JSON 中使用中文标点符号（如：，、：等）
5. 字符串值中如果包含引号，请使用转义符 \\"
6. 布尔值使用 true/false，不要使用字符串

返回格式示例：
{"tables":[{"name":"users","comment":"用户表","fields":[{"name":"id","type":"Integer","isPrimary":true,"isForeign":false,"isNullable":false,"comment":"主键ID"}]}],"relations":[{"fromTable":"orders","fromField":"user_id","toTable":"users","toField":"id","relationType":"N:1"}]}

通用设计原则：
- 每个表必须有主键
- 外键字段命名通常为 {关联表名}_id
- 为关键字段添加索引
- 添加必要的审计字段如 created_at、updated_at
- 关系类型包括：1:1（一对一）、1:N（一对多）、N:M（多对多）
- 对于多对多关系，需要创建中间关联表
- 字段类型请使用通用的描述（如 String, Integer, DateTime），后续会转换为特定数据库语法

请严格按照上述格式返回完整的 JSON 对象。`
}

// Stage 4: SQL Generation
export function getSqlGenerationPrompt(databaseType: string, tables: any[], relations: any[]): string {
  const dbSyntax = DATABASE_SYNTAX[databaseType] || DATABASE_SYNTAX['mysql']

  return `你是一个资深的数据库开发工程师。
请根据以下表结构设计，生成符合 ${databaseType.toUpperCase()} 语法的建表语句。

表结构设计：
${JSON.stringify({ tables, relations }, null, 2)}

【极度重要】：
请直接返回完整的 SQL 建表语句，不要任何解释性文字！不要返回 JSON 格式！

数据库特定语法要求 (${databaseType.toUpperCase()})：
${dbSyntax}
`
}

// Stage 5: Documentation Generation (旧版，供 ≤8 表使用)
export function getDocumentGenerationPrompt(tables: any[], relations: any[]): string {
  const template = `# 数据库设计文档

## 1. 设计概览
<业务目标、设计范围、关键假设概述>

## 2. 实体清单
| 表名 | 中文名/注释 | 说明 |
|---|---|---|
|  |  |  |

## 3. 数据字典
### 3.1 表：<表名>
- 表作用：<一句话说明该表承载的业务对象与用途>

| 字段名 | 中文名/注释 | 类型 | 主键 | 外键 | 可空 | 说明 |
|---|---|---|---|---|---|---|
|  |  |  |  |  |  |  |

## 4. 表关系说明
| 源表 | 源字段 | 目标表 | 目标字段 | 关系类型 | 说明 |
|---|---|---|---|---|---|
|  |  |  |  |  |  |

## 5. 设计决策说明
<拆表/合表原因、范式选择、审计字段策略等>

## 6. 索引与查询建议
<主键/外键索引、高频查询模式建议>

## 7. 安全与数据完整性
<敏感字段提示、唯一约束、软删除策略>

## 8. 扩展与迁移建议
<未来扩展方向、分区/归档建议>
`

  return `你是一个资深数据库文档工程师，请基于用户消息中提供的表结构和关系数据，生成一份完整、专业、可直接交付的数据库设计文档。

必须使用以下模板结构与表头：
${template}

生成规则：
1) 必须保留全部一级和二级章节标题，不允许改名。
2) 第 1-4 章为核心章节，必须完整填写，不允许省略。
3) 第 5-8 章为建议章节，根据数据复杂度自行判断是否生成，如无相关内容可省略。
4) "实体清单""数据字典""表关系说明"必须是 Markdown 表格，表头不可改。
5) "实体清单"的"说明"列必须写该表业务作用，禁止留空或只重复表名。
6) 每个"### 3.x 表：..."后必须有一行"表作用：..."，说明该表的业务用途。
7) "设计决策说明"需结合表结构给出具体分析，如：为什么拆分为多张表、为什么采用某种关系类型、审计字段设计思路等。
8) "索引与查询建议"需列出建议创建的索引字段和适用的查询场景。
9) "安全与数据完整性"需指出敏感字段（如密码、手机号）的保护建议、唯一约束、软删除策略等。
10) "扩展与迁移建议"需给出未来可能的扩展方向和数据迁移注意事项。
11) 信息不足可写"暂无"，但不得省略核心章节。
12) 每个说明要写实质性内容，避免空洞泛化描述。

只返回 Markdown 正文，不要解释，不要代码块。`
}

export function getDocumentRepairPrompt(rawDocument: string): string {
  return `你是一个文档格式修复助手。请将给定文档重排为标准模板并保留有效信息。

必须保留并按顺序输出以下章节标题：
# 数据库设计文档
## 1. 设计概览
## 2. 实体清单
## 3. 数据字典
## 4. 表关系说明

可选章节（如原始文档包含相关内容则保留，否则省略）：
## 5. 设计决策说明
## 6. 索引与查询建议
## 7. 安全与数据完整性
## 8. 扩展与迁移建议

必须使用以下表头（不得改名）：
- 实体清单：表名 | 中文名/注释 | 说明
- 数据字典：字段名 | 中文名/注释 | 类型 | 主键 | 外键 | 可空 | 说明
- 表关系说明：源表 | 源字段 | 目标表 | 目标字段 | 关系类型 | 说明

每个"### 3.x 表：..."小节必须包含"表作用：..."说明该表的业务用途。

原始文档：
${rawDocument}

只返回修复后的 Markdown 正文，不要任何解释。`
}

export function getJsonRepairPrompt(content: string): string {
  const repairSource = content.length > 16000 ? content.slice(0, 16000) : content
  return `以下是一个格式错误的 JSON，请修复它并返回正确的 JSON 格式。只返回修复后的 JSON，不要任何解释。

错误的 JSON：
${repairSource}

请返回修复后的完整 JSON 对象。`
}

// === 分段文档生成 Prompt（大型系统 >8 表时使用） ===

// Part A: 设计概览 + 实体清单
export function getDocOverviewPrompt(databaseType: string, tableCount: number): string {
  return `你是一个资深数据库文档工程师。
请根据用户消息中的表列表和业务需求，生成"设计概览"和"实体清单"两个章节。

生成规则：
1) 只输出以下两个章节，不要输出其他章节：
   ## 1. 设计概览
   ## 2. 实体清单
2) "设计概览"需写明：业务目标、设计范围（共 ${tableCount} 张表）、关键设计假设。
3) "实体清单"必须是 Markdown 表格，表头为：| 表名 | 中文名/注释 | 说明 |
4) "说明"列必须写该表的业务作用，禁止留空或只重复表名。
5) 使用中文，语义准确，内容具体。

只返回这两个章节的 Markdown 正文，不要解释，不要代码块。`
}

// Part B: 数据字典（一批表）
export function getDocDictionaryPrompt(databaseType: string, batchIndex: number, totalBatches: number): string {
  return `你是一个资深数据库文档工程师。
请根据用户消息中的表结构数据，生成这批表的"数据字典"章节内容。
这是第 ${batchIndex + 1}/${totalBatches} 批。

生成规则：
1) 只输出数据字典章节内容，不要输出其他章节。
2) 每张表使用 "### 表：<表名>" 作为小节标题（编号由外部系统统一处理，你无需编号）。
3) 每个小节后必须有一行"表作用：..."，说明该表的业务用途。
4) 每个小节必须包含字段表格，表头为：| 字段名 | 中文名/注释 | 类型 | 主键 | 外键 | 可空 | 说明 |
5) 主键/外键列填"是"或"否"，可空列填"是"或"否"。
6) "说明"列必须写该字段的业务含义，禁止留空或只重复字段名。
7) 使用中文，语义准确，内容具体。

只返回数据字典 Markdown 正文，不要解释，不要代码块。`
}

// Part C: 表关系说明 + 可选建议章节
export function getDocRelationsPrompt(databaseType: string, tableCount: number): string {
  return `你是一个资深数据库文档工程师。
请根据用户消息中的表关系数据，生成"表关系说明"及可选的建议类章节。
这是文档的最后一个部分。

生成规则：
1) 必须输出：
   ## 4. 表关系说明
2) "表关系说明"必须是 Markdown 表格，表头为：| 源表 | 源字段 | 目标表 | 目标字段 | 关系类型 | 说明 |
3) "说明"列需描述该关系的业务含义，禁止留空。
4) 根据数据复杂度自行判断是否输出以下可选章节（有内容则写，无内容则省略）：
   ## 5. 设计决策说明
   ## 6. 索引与查询建议
   ## 7. 安全与数据完整性
   ## 8. 扩展与迁移建议
5) 使用中文，语义准确，内容具体。

只返回上述章节的 Markdown 正文，不要解释，不要代码块。`
}
