import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'

// Allow for longer timeouts
export const maxDuration = 300; // 5 minutes

// 数据库特定的 SQL 语法指南
const DATABASE_SYNTAX: Record<string, string> = {
  mysql: `
- 使用 MySQL 语法
- 自增主键使用 AUTO_INCREMENT
- 字符串类型使用 VARCHAR(n)，大文本使用 TEXT
- 日期时间使用 DATETIME、TIMESTAMP
- 注释使用 COMMENT 关键字
- 引擎推荐使用 InnoDB: ENGINE=InnoDB
- 字符集推荐 utf8mb4: DEFAULT CHARSET=utf8mb4
- 示例: CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL COMMENT '用户名') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';
`,
  postgresql: `
- 使用 PostgreSQL 语法
- 自增主键使用 SERIAL 或 BIGSERIAL
- 字符串类型使用 VARCHAR(n)，大文本使用 TEXT
- 日期时间使用 TIMESTAMP、TIMESTAMPTZ
- 注释使用 COMMENT ON 语句
- 支持 UUID 类型
- 示例: CREATE TABLE users (id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL);
COMMENT ON TABLE users IS '用户表';
COMMENT ON COLUMN users.name IS '用户名';
`,
  sqlite: `
- 使用 SQLite 语法
- 自增主键使用 INTEGER PRIMARY KEY AUTOINCREMENT
- 字符串类型使用 TEXT（无长度限制）
- 日期时间使用 TEXT 或 DATETIME
- SQLite 不支持 COMMENT 关键字，字段注释放在字段名后用 -- 注释
- 数据类型简化: INTEGER、TEXT、REAL、BLOB
- 示例: CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL -- 用户名);
`,
  sqlserver: `
- 使用 SQL Server (T-SQL) 语法
- 自增主键使用 IDENTITY(1,1)
- 字符串类型使用 NVARCHAR(n)，大文本使用 NVARCHAR(MAX)
- 日期时间使用 DATETIME、DATETIME2
- 注释使用 EXEC sp_addextendedproperty 存储过程
- 支持 UNIQUEIDENTIFIER 类型 (GUID)
- 示例: CREATE TABLE users (id INT IDENTITY(1,1) PRIMARY KEY, name NVARCHAR(100) NOT NULL);
EXEC sp_addextendedproperty 'MS_Description', '用户表', 'SCHEMA', 'dbo', 'TABLE', 'users';
`,
  oracle: `
- 使用 Oracle 语法
- 自增主键使用序列 (SEQUENCE) + 触发器 (TRIGGER) 或 IDENTITY 列 (12c+)
- 字符串类型使用 VARCHAR2(n)，大文本使用 CLOB
- 日期时间使用 DATE、TIMESTAMP
- 注释使用 COMMENT ON 语句
- 表名、字段名推荐使用大写
- 示例: CREATE TABLE USERS (ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, NAME VARCHAR2(100) NOT NULL);
COMMENT ON TABLE USERS IS '用户表';
`,
  mariadb: `
- 使用 MariaDB 语法（与 MySQL 高度兼容）
- 自增主键使用 AUTO_INCREMENT
- 字符串类型使用 VARCHAR(n)，大文本使用 TEXT
- 日期时间使用 DATETIME、TIMESTAMP
- 注释使用 COMMENT 关键字
- 引擎推荐使用 InnoDB: ENGINE=InnoDB
- 字符集推荐 utf8mb4: DEFAULT CHARSET=utf8mb4
- 示例: CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL COMMENT '用户名') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';
`,
  clickhouse: `
- 使用 ClickHouse 语法
- 主键使用 PRIMARY KEY，排序使用 ORDER BY
- 字符串类型使用 String
- 日期时间使用 DateTime、Date
- 注释使用 COMMENT 关键字
- 必须指定 Engine，常用 MergeTree 系列
- 示例: CREATE TABLE users (id UInt64, name String NOT NULL COMMENT '用户名', created_at DateTime DEFAULT now()) ENGINE = MergeTree() ORDER BY id COMMENT '用户表';
`
}

function getSystemPrompt(databaseType: string): string {
  const dbSyntax = DATABASE_SYNTAX[databaseType] || DATABASE_SYNTAX['mysql']
  
  return `你是一个资深的数据库架构师，擅长根据产品需求设计数据库表结构。

当用户输入产品需求描述时，你需要：
1. 分析需求，提取核心功能关键点
2. 设计合理的数据库表结构
3. 定义表之间的关系
4. 生成符合 ${databaseType.toUpperCase()} 语法的建表语句

请严格按照以下JSON格式返回结果，**不要包含任何 markdown 格式（如 \`\`\`json ... \`\`\`），不要包含任何额外的解释文字，直接返回纯 JSON 字符串**：

{
  "keyPoints": ["关键点1", "关键点2", ...],
  "tables": [
    {
      "name": "表名",
      "comment": "表注释说明",
      "fields": [
        {
          "name": "字段名",
          "type": "字段类型",
          "isPrimary": false,
          "isForeign": false,
          "isNullable": true,
          "comment": "字段注释"
        }
      ]
    }
  ],
  "relations": [
    {
      "fromTable": "源表名",
      "fromField": "源字段名",
      "toTable": "目标表名",
      "toField": "目标字段名",
      "relationType": "1:N 或 1:1 或 N:M"
    }
  ],
  "sqlStatements": "完整的SQL建表语句"
}

数据库特定语法要求 (${databaseType.toUpperCase()})：
${dbSyntax}

通用设计原则：
- 每个表必须有主键
- 外键字段命名通常为 {关联表名}_id
- 为关键字段添加索引
- 添加必要的审计字段如 created_at、updated_at
- 关系类型包括：1:1（一对一）、1:N（一对多）、N:M（多对多）
- 对于多对多关系，需要创建中间关联表

请确保返回的是有效的JSON格式，不要包含markdown代码块标记。`
}

interface LLMConfig {
  provider: string
  apiKey: string
  baseUrl: string | null
  model: string
  temperature: number
  maxTokens: number
  databaseType: string
}

async function callLLM(config: LLMConfig, userMessage: string): Promise<string> {
  const baseUrl = config.baseUrl || 'https://api.openai.com/v1'
  const url = `${baseUrl}/chat/completions`

  const systemPrompt = getSystemPrompt(config.databaseType)

  const controller = new AbortController()
  const timeoutId = setTimeout(() => controller.abort(), 300000) // 300s timeout

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${config.apiKey}`
      },
      body: JSON.stringify({
        model: config.model,
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userMessage }
        ],
        temperature: config.temperature,
        max_tokens: config.maxTokens
      }),
      signal: controller.signal
    })

    clearTimeout(timeoutId)

    if (!response.ok) {
      const errorText = await response.text()
      throw new Error(`LLM API 调用失败: ${response.status} - ${errorText}`)
    }

    let data
    try {
      const text = await response.text()
      try {
        data = JSON.parse(text)
      } catch (e) {
        console.error('LLM API returned non-JSON response:', text)
        // 如果返回的是 HTML，尝试提取错误信息
        if (text.includes('<!DOCTYPE html>') || text.includes('<html>')) {
          const titleMatch = text.match(/<title>(.*?)<\/title>/)
          const title = titleMatch ? titleMatch[1] : 'Unknown HTML Error'
          throw new Error(`LLM API 返回了 HTML 错误页面: ${title}`)
        }
        throw new Error(`LLM API 返回了非 JSON 格式的数据: ${text.slice(0, 100)}...`)
      }
    } catch (error) {
      throw error
    }

    const content = data.choices?.[0]?.message?.content
    if (!content) {
       throw new Error('LLM API 返回的数据格式不正确，缺少 choices[0].message.content')
    }

    return content
  } catch (error) {
    clearTimeout(timeoutId)
    if (error instanceof Error && error.name === 'AbortError') {
      throw new Error('LLM API 调用超时 (300s)，请尝试简化需求或稍后重试')
    }
    throw error
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { requirement } = body

    if (!requirement || typeof requirement !== 'string') {
      return NextResponse.json(
        { error: '请提供有效的需求描述' },
        { status: 400 }
      )
    }

    // 获取 LLM 配置
    const llmConfig = await db.lLMConfig.findFirst({
      where: { isActive: true }
    })

    if (!llmConfig || !llmConfig.apiKey) {
      return NextResponse.json(
        { error: '请先配置 LLM 服务', needConfig: true },
        { status: 400 }
      )
    }

    // 检查是否有缓存的成功记录 (最近 24 小时内的相同需求)
    const cachedHistory = await db.history.findFirst({
      where: {
        question: requirement,
        status: 'success',
        databaseType: llmConfig.databaseType || 'mysql',
        createdAt: {
          gte: new Date(Date.now() - 24 * 60 * 60 * 1000) // 24 hours ago
        }
      },
      orderBy: {
        createdAt: 'desc'
      }
    })

    if (cachedHistory) {
      try {
        const cachedResult = JSON.parse(cachedHistory.result)
        // 更新历史记录时间，使其出现在顶部
        await db.history.update({
          where: { id: cachedHistory.id },
          data: { createdAt: new Date() }
        })
        return NextResponse.json(cachedResult)
      } catch (e) {
        console.error('Failed to parse cached result:', e)
        // 如果解析失败，继续执行 LLM 调用
      }
    }

    // 调用 LLM
    const responseContent = await callLLM(
      {
        provider: llmConfig.provider,
        apiKey: llmConfig.apiKey,
        baseUrl: llmConfig.baseUrl,
        model: llmConfig.model,
        temperature: llmConfig.temperature,
        maxTokens: llmConfig.maxTokens,
        databaseType: llmConfig.databaseType || 'mysql'
      },
      `请分析以下产品需求，设计数据库表结构：\n\n${requirement}`
    )

    if (!responseContent) {
      return NextResponse.json(
        { error: 'AI 分析返回为空' },
        { status: 500 }
      )
    }

    // 解析 JSON 响应
    let result
    try {
      // 更加健壮的 JSON 提取逻辑
      let cleanedContent = responseContent.trim()
      
      // 1. 尝试匹配 ```json ... ``` 代码块
      const jsonBlockMatch = cleanedContent.match(/```json\s*([\s\S]*?)\s*```/)
      if (jsonBlockMatch) {
        cleanedContent = jsonBlockMatch[1]
      } else {
        // 2. 尝试匹配 ``` ... ``` 代码块
        const codeBlockMatch = cleanedContent.match(/```\s*([\s\S]*?)\s*```/)
        if (codeBlockMatch) {
          cleanedContent = codeBlockMatch[1]
        }
      }

      // 3. 如果还是无法解析，尝试提取最外层的 {}
      // 这一步是为了应对开头或结尾有额外文字的情况
      const firstBrace = cleanedContent.indexOf('{')
      const lastBrace = cleanedContent.lastIndexOf('}')
      if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
        cleanedContent = cleanedContent.substring(firstBrace, lastBrace + 1)
      }

      result = JSON.parse(cleanedContent)
    } catch (parseError) {
      console.error('Failed to parse JSON:', parseError)
      console.error('Response content:', responseContent)
      return NextResponse.json(
        { error: 'AI 返回格式解析失败，请重试' },
        { status: 500 }
      )
    }

    // 验证结果结构
    if (!result.keyPoints || !Array.isArray(result.keyPoints)) {
      result.keyPoints = []
    }
    if (!result.tables || !Array.isArray(result.tables)) {
      result.tables = []
    }
    if (!result.relations || !Array.isArray(result.relations)) {
      result.relations = []
    }
    if (!result.sqlStatements) {
      result.sqlStatements = ''
    }

    // 添加数据库类型信息到结果中
    result.databaseType = llmConfig.databaseType || 'mysql'

    // 保存问答历史
    try {
      await db.history.create({
        data: {
          question: requirement,
          result: JSON.stringify(result),
          databaseType: llmConfig.databaseType || 'mysql',
          provider: llmConfig.provider,
          model: llmConfig.model,
          status: 'success'
        }
      })
    } catch (historyError) {
      console.error('Failed to save history:', historyError)
      // 不阻塞主流程
    }

    return NextResponse.json(result)

  } catch (error) {
    console.error('Analysis error:', error)
    const errorMessage = error instanceof Error ? error.message : '分析过程中出现错误，请稍后重试'
    
    // 尝试保存失败记录（如果能获取到 LLM 配置）
    try {
      const body = await request.clone().json().catch(() => ({}))
      const { requirement } = body
      if (requirement) {
         // 获取 LLM 配置 (再次尝试获取，因为外层的 llmConfig 作用域可能不在这里，或者为了简单直接重新查询)
         // 为了避免复杂性，这里简单处理，如果上面没获取到配置，这里可能也获取不到，或者我们可以把 llmConfig 提到 try 外面
         // 但为了代码最小改动，我们这里只在有 requirement 时尝试记录
         // 实际生产环境应该优化这里的逻辑
      }
    } catch (e) {
      // 忽略
    }

    return NextResponse.json(
      { error: errorMessage },
      { status: 500 }
    )
  }
}
