import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'

// Allow for longer timeouts
export const maxDuration = 300; // 5 minutes

// 数据库特定的 SQL 语法指南
const DATABASE_SYNTAX: Record<string, string> = {
  mysql: `
- 使用 MySQL 语法
- 自增主键使用 AUTO_INCREMENT
- 字符串类型使用 VARCHAR(n)，大文本使用 TEXT
- 日期时间使用 DATETIME、TIMESTAMP
- 注释使用 COMMENT 关键字
- 引擎推荐使用 InnoDB: ENGINE=InnoDB
- 字符集推荐 utf8mb4: DEFAULT CHARSET=utf8mb4
- 示例: CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL COMMENT '用户名') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';
`,
  postgresql: `
- 使用 PostgreSQL 语法
- 自增主键使用 SERIAL 或 BIGSERIAL
- 字符串类型使用 VARCHAR(n)，大文本使用 TEXT
- 日期时间使用 TIMESTAMP、TIMESTAMPTZ
- 注释使用 COMMENT ON 语句
- 支持 UUID 类型
- 示例: CREATE TABLE users (id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL);
COMMENT ON TABLE users IS '用户表';
COMMENT ON COLUMN users.name IS '用户名';
`,
  sqlite: `
- 使用 SQLite 语法
- 自增主键使用 INTEGER PRIMARY KEY AUTOINCREMENT
- 字符串类型使用 TEXT（无长度限制）
- 日期时间使用 TEXT 或 DATETIME
- SQLite 不支持 COMMENT 关键字，字段注释放在字段名后用 -- 注释
- 数据类型简化: INTEGER、TEXT、REAL、BLOB
- 示例: CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL -- 用户名);
`,
  sqlserver: `
- 使用 SQL Server (T-SQL) 语法
- 自增主键使用 IDENTITY(1,1)
- 字符串类型使用 NVARCHAR(n)，大文本使用 NVARCHAR(MAX)
- 日期时间使用 DATETIME、DATETIME2
- 注释使用 EXEC sp_addextendedproperty 存储过程
- 支持 UNIQUEIDENTIFIER 类型 (GUID)
- 示例: CREATE TABLE users (id INT IDENTITY(1,1) PRIMARY KEY, name NVARCHAR(100) NOT NULL);
EXEC sp_addextendedproperty 'MS_Description', '用户表', 'SCHEMA', 'dbo', 'TABLE', 'users';
`,
  oracle: `
- 使用 Oracle 语法
- 自增主键使用序列 (SEQUENCE) + 触发器 (TRIGGER) 或 IDENTITY 列 (12c+)
- 字符串类型使用 VARCHAR2(n)，大文本使用 CLOB
- 日期时间使用 DATE、TIMESTAMP
- 注释使用 COMMENT ON 语句
- 表名、字段名推荐使用大写
- 示例: CREATE TABLE USERS (ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, NAME VARCHAR2(100) NOT NULL);
COMMENT ON TABLE USERS IS '用户表';
`,
  mariadb: `
- 使用 MariaDB 语法（与 MySQL 高度兼容）
- 自增主键使用 AUTO_INCREMENT
- 字符串类型使用 VARCHAR(n)，大文本使用 TEXT
- 日期时间使用 DATETIME、TIMESTAMP
- 注释使用 COMMENT 关键字
- 引擎推荐使用 InnoDB: ENGINE=InnoDB
- 字符集推荐 utf8mb4: DEFAULT CHARSET=utf8mb4
- 示例: CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL COMMENT '用户名') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';
`,
  clickhouse: `
- 使用 ClickHouse 语法
- 主键使用 PRIMARY KEY，排序使用 ORDER BY
- 字符串类型使用 String
- 日期时间使用 DateTime、Date
- 注释使用 COMMENT 关键字
- 必须指定 Engine，常用 MergeTree 系列
- 示例: CREATE TABLE users (id UInt64, name String NOT NULL COMMENT '用户名', created_at DateTime DEFAULT now()) ENGINE = MergeTree() ORDER BY id COMMENT '用户表';
`
}

// Stage 1: Requirement Optimization
function getRequirementOptimizationPrompt(): string {
  return `你是一个资深的产品经理兼业务架构师。
用户输入的产品需求往往是口语化、简短或缺乏细节的。你的任务是接收用户的原始需求，结合行业经验，对其进行**脑补、细化和专业化翻译**。
你需要补充潜在的业务逻辑、隐式需求（例如：必要的审计字段、权限控制、状态流转、软删除等），输出一段详细、结构化的标准业务需求描述，以便后续的数据库架构师能根据你的描述设计出健壮的表结构。

【极度重要】：
请直接返回详细的业务需求描述，不要任何解释性文字！不要返回 JSON 格式！`
}

// Stage 2: Requirement Analysis
function getAnalysisPrompt(): string {
  return `你是一个资深的业务分析师。
请分析用户的产品需求描述，提取出核心功能关键点。
关键点必须是可映射为数据库建模的内容，禁止输出 UI、样式、页面交互等无关信息。

【极度重要】：
你必须且只能返回一个合法的 JSON 对象！绝对不要输出其他解释性文字！
不要输出 markdown，不要输出代码块，不要输出任何 JSON 之外的字符。

请严格按照以下JSON格式返回结果，**不要包含任何 markdown 格式，直接返回纯 JSON 字符串**：
{
  "keyPoints": ["关键点1", "关键点2", ...]
}`
}

// Stage 3: Schema Design
function getSchemaDesignPrompt(databaseType: string, keyPoints: string[]): string {
  return `你是一个资深的数据库架构师。
基于以下业务关键点，设计合理的数据库表结构和关系。
业务关键点：
${keyPoints.map(p => `- ${p}`).join('\n')}

【极度重要】：
你必须且只能返回一个合法的 JSON 对象！绝对不要输出其他解释性文字或直接输出 SQL！
不要输出 markdown，不要输出代码块，不要输出任何 JSON 之外的字符。

请严格按照以下JSON格式返回结果，**不要包含任何 markdown 格式，直接返回纯 JSON 字符串**：
{
  "tables": [
    {
      "name": "表名",
      "comment": "表注释说明",
      "fields": [
        {
          "name": "字段名",
          "type": "字段类型",
          "isPrimary": false,
          "isForeign": false,
          "isNullable": true,
          "comment": "字段注释"
        }
      ]
    }
  ],
  "relations": [
    {
      "fromTable": "源表名",
      "fromField": "源字段名",
      "toTable": "目标表名",
      "toField": "目标字段名",
      "relationType": "1:N 或 1:1 或 N:M"
    }
  ]
}

通用设计原则：
- 每个表必须有主键
- 外键字段命名通常为 {关联表名}_id
- 为关键字段添加索引
- 添加必要的审计字段如 created_at、updated_at
- 关系类型包括：1:1（一对一）、1:N（一对多）、N:M（多对多）
- 对于多对多关系，需要创建中间关联表
- 字段类型请使用通用的描述（如 String, Integer, DateTime），后续会转换为特定数据库语法`
}

// Stage 4: SQL Generation
function getSqlGenerationPrompt(databaseType: string, tables: any[], relations: any[]): string {
  const dbSyntax = DATABASE_SYNTAX[databaseType] || DATABASE_SYNTAX['mysql']
  
  return `你是一个资深的数据库开发工程师。
请根据以下表结构设计，生成符合 ${databaseType.toUpperCase()} 语法的建表语句。

表结构设计：
${JSON.stringify({ tables, relations }, null, 2)}

【极度重要】：
请直接返回完整的 SQL 建表语句，不要任何解释性文字！不要返回 JSON 格式！

数据库特定语法要求 (${databaseType.toUpperCase()})：
${dbSyntax}
`
}

// Stage 5: Documentation Generation
function getDocumentGenerationPrompt(tables: any[], relations: any[]): string {
  return `你是一个资深的技术文档工程师。
请根据以下表结构设计，编写一份标准的数据库设计文档。

表结构设计：
${JSON.stringify({ tables, relations }, null, 2)}

【极度重要】：
请直接返回完整的数据库设计文档（Markdown格式，使用 # 等标题层级，对于数据字典和表关系请使用标准的 Markdown 表格形式展示），不要任何解释性文字！不要返回 JSON 格式！
`
}

interface LLMConfig {
  provider: string
  apiKey: string
  baseUrl: string | null
  model: string
  temperature: number
  maxTokens: number
  databaseType: string
}

type AnalyzeStage = 'optimization' | 'analysis' | 'design' | 'sql_generation' | 'doc_generation'

interface CallLLMOptions {
  timeoutMs: number
  maxRetries: number
  stageName: AnalyzeStage
}

const ANALYZE_TOTAL_BUDGET_MS = 270000
const HEARTBEAT_INTERVAL_MS = 12000
const STAGE_TIMEOUT_MS: Record<AnalyzeStage, number> = {
  optimization: 50000,
  analysis: 40000,
  design: 70000,
  sql_generation: 60000,
  doc_generation: 50000
}

function sleep(ms: number) {
  return new Promise(resolve => setTimeout(resolve, ms))
}

function getRemainingBudgetMs(startTime: number): number {
  return ANALYZE_TOTAL_BUDGET_MS - (Date.now() - startTime)
}

function getCallOptions(stageName: AnalyzeStage, startTime: number): CallLLMOptions {
  const remaining = getRemainingBudgetMs(startTime)
  if (remaining <= 15000) {
    throw new Error('分析总耗时已接近上限，请简化需求后重试')
  }
  const timeoutMs = Math.max(15000, Math.min(STAGE_TIMEOUT_MS[stageName], remaining - 5000))
  return {
    timeoutMs,
    maxRetries: 1,
    stageName
  }
}

function extractContentText(content: unknown): string {
  if (typeof content === 'string') return content
  if (Array.isArray(content)) {
    return content
      .map(item => {
        if (typeof item === 'string') return item
        if (item && typeof item === 'object' && 'text' in item) {
          const text = (item as { text?: unknown }).text
          return typeof text === 'string' ? text : ''
        }
        return ''
      })
      .join('')
  }
  return ''
}

function extractBalancedJsonObject(input: string): string | null {
  const text = input.trim()
  const startIndex = text.indexOf('{')
  if (startIndex === -1) return null

  let depth = 0
  let inString = false
  let escaped = false

  for (let i = startIndex; i < text.length; i++) {
    const char = text[i]
    if (inString) {
      if (escaped) {
        escaped = false
      } else if (char === '\\') {
        escaped = true
      } else if (char === '"') {
        inString = false
      }
      continue
    }

    if (char === '"') {
      inString = true
      continue
    }

    if (char === '{') depth++
    if (char === '}') {
      depth--
      if (depth === 0) {
        return text.slice(startIndex, i + 1)
      }
    }
  }

  return null
}

function parseStructuredJsonContent(raw: string): any {
  let cleanedContent = raw.trim()
  const jsonBlockMatch = cleanedContent.match(/```json\s*([\s\S]*?)\s*```/)
  if (jsonBlockMatch) {
    cleanedContent = jsonBlockMatch[1]
  } else {
    const codeBlockMatch = cleanedContent.match(/```\s*([\s\S]*?)\s*```/)
    if (codeBlockMatch) {
      cleanedContent = codeBlockMatch[1]
    }
  }

  const balancedJson = extractBalancedJsonObject(cleanedContent)
  if (balancedJson) {
    cleanedContent = balancedJson
  }

  const candidates = [
    cleanedContent,
    cleanedContent.replace(/,\s*([}\]])/g, '$1')
  ]

  for (const candidate of candidates) {
    try {
      return JSON.parse(candidate)
    } catch {}
  }

  throw new Error('Failed to parse LLM response as JSON')
}

function isSqlContentValid(sql: string): boolean {
  const normalized = sql.toUpperCase()
  if (normalized.length < 20) return false
  return /(CREATE\s+(TABLE|INDEX|SEQUENCE|VIEW)|ALTER\s+TABLE|DROP\s+TABLE)/.test(normalized)
}

async function extractContentFromStandardResponse(response: Response): Promise<string> {
  const text = await response.text()
  let data
  try {
    data = JSON.parse(text)
  } catch (e) {
    console.error('LLM API returned non-JSON response:', text)
    throw new Error(`LLM API returned invalid JSON: ${text.slice(0, 100)}...`)
  }
  const content = extractContentText(data?.choices?.[0]?.message?.content)
  if (!content) {
    throw new Error('LLM API returned empty content')
  }
  return content
}

async function extractContentFromStreamResponse(response: Response): Promise<string> {
  if (!response.body) {
    throw new Error('LLM API 返回了空响应流')
  }

  const reader = response.body.getReader()
  const decoder = new TextDecoder()
  let buffer = ''
  let content = ''

  while (true) {
    const { done, value } = await reader.read()
    if (done) {
      buffer += decoder.decode()
    } else {
      buffer += decoder.decode(value, { stream: true })
    }

    const events = buffer.split('\n\n')
    buffer = events.pop() || ''

    for (const eventBlock of events) {
      const dataLines = eventBlock
        .split('\n')
        .map(line => line.trim())
        .filter(line => line.startsWith('data:'))
        .map(line => line.slice(5).trimStart())

      if (dataLines.length === 0) continue
      const payload = dataLines.join('\n').trim()
      if (!payload) continue
      if (payload === '[DONE]') {
        return content.trim()
      }

      let chunk: any
      try {
        chunk = JSON.parse(payload)
      } catch {
        continue
      }

      if (chunk?.error?.message) {
        throw new Error(chunk.error.message)
      }

      const deltaText = extractContentText(chunk?.choices?.[0]?.delta?.content)
      const messageText = extractContentText(chunk?.choices?.[0]?.message?.content)

      if (deltaText) {
        content += deltaText
      } else if (messageText) {
        const normalizedMessageText = messageText.trim()
        if (normalizedMessageText.startsWith(content.trim())) {
          content = normalizedMessageText
        } else {
          content += messageText
        }
      }
    }

    if (done) break
  }

  if (!content) {
    throw new Error('LLM API returned empty content')
  }
  return content
}

async function callLLM(
  config: LLMConfig, 
  systemPrompt: string, 
  userMessage: string, 
  expectJson: boolean = true, 
  textKey?: string,
  options: CallLLMOptions = { timeoutMs: 120000, maxRetries: 1, stageName: 'analysis' },
  retryCount: number = 0
): Promise<any> {
  const baseUrl = config.baseUrl || 'https://api.openai.com/v1'
  const url = `${baseUrl}/chat/completions`
  const useStream = true

  const controller = new AbortController()
  const timeoutId = setTimeout(() => controller.abort(), options.timeoutMs)

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${config.apiKey}`
      },
      body: JSON.stringify({
        model: config.model,
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userMessage }
        ],
        stream: useStream,
        temperature: config.temperature,
        max_tokens: config.maxTokens
      }),
      signal: controller.signal
    })

    clearTimeout(timeoutId)

    if (!response.ok) {
      const errorText = await response.text()
      if ((response.status === 429 || response.status >= 500) && retryCount < options.maxRetries) {
        const backoff = 1200 * (retryCount + 1) + Math.floor(Math.random() * 400)
        await sleep(backoff)
        return callLLM(config, systemPrompt, userMessage, expectJson, textKey, options, retryCount + 1)
      }
      throw new Error(`LLM API 调用失败: ${response.status} - ${errorText}`)
    }

    const content = useStream
      ? await extractContentFromStreamResponse(response)
      : await extractContentFromStandardResponse(response)

    if (!expectJson && textKey) {
        let cleanedContent = content.trim()
        cleanedContent = cleanedContent.replace(/^```[\w]*\n?/i, '')
                                       .replace(/\n?```$/i, '')
                                       .trim()
        if (textKey === 'sqlStatements' && !isSqlContentValid(cleanedContent)) {
          throw new Error('SQL结果校验失败：未检测到有效 DDL 语句')
        }
        return { [textKey]: cleanedContent }
    }

    try {
      return parseStructuredJsonContent(content)
    } catch (e) {
      const normalizedContent = content.trim()
      const parseSample = normalizedContent.slice(0, 300).replace(/\s+/g, ' ')
      console.error(`[${options.stageName}] JSON parse failed sample:`, parseSample)
      // 容错处理：如果模型没有返回 JSON 而是直接返回了 SQL 代码（通常包含 CREATE TABLE 或 CREATE DATABASE）
      if (!normalizedContent.includes('{') && (normalizedContent.toUpperCase().includes('CREATE TABLE') || normalizedContent.toUpperCase().includes('CREATE DATABASE'))) {
        return {
          sqlStatements: content.replace(/```sql/gi, '').replace(/```/g, '').replace(/^sql\n/i, '').trim()
        }
      }
      // 容错处理：如果是文档生成阶段返回了纯 Markdown
      if (!normalizedContent.includes('{') && normalizedContent.includes('#')) {
         return {
            designDocument: content.replace(/```markdown/gi, '').replace(/```/g, '').trim()
         }
      }
      throw new Error(`Failed to parse LLM response as JSON (stage: ${options.stageName})`)
    }

  } catch (error) {
    clearTimeout(timeoutId)
    if (error instanceof Error && error.name === 'AbortError') {
      if (retryCount < options.maxRetries) {
        const backoff = 1200 * (retryCount + 1) + Math.floor(Math.random() * 400)
        await sleep(backoff)
        return callLLM(config, systemPrompt, userMessage, expectJson, textKey, options, retryCount + 1)
      }
      throw new Error(`阶段 ${options.stageName} 调用超时（${Math.floor(options.timeoutMs / 1000)}秒），请重试或简化需求`)
    }
    if (error instanceof Error && retryCount < options.maxRetries) {
      const causeCode = (error as Error & { cause?: { code?: string } }).cause?.code
      const lowerMessage = error.message.toLowerCase()
      const isRetryableNetworkError = causeCode === 'UND_ERR_CONNECT_TIMEOUT'
        || lowerMessage.includes('fetch failed')
        || lowerMessage.includes('network')
        || lowerMessage.includes('connect timeout')
      const isRetryableParseError = lowerMessage.includes('failed to parse llm response as json')
      const isRetryableSqlValidationError = options.stageName === 'sql_generation' && lowerMessage.includes('sql结果校验失败')
      if (isRetryableNetworkError) {
        const backoff = 1200 * (retryCount + 1) + Math.floor(Math.random() * 400)
        await sleep(backoff)
        return callLLM(config, systemPrompt, userMessage, expectJson, textKey, options, retryCount + 1)
      }
      if (isRetryableParseError) {
        const backoff = 800 * (retryCount + 1) + Math.floor(Math.random() * 300)
        await sleep(backoff)
        return callLLM(config, systemPrompt, userMessage, expectJson, textKey, options, retryCount + 1)
      }
      if (isRetryableSqlValidationError) {
        const backoff = 800 * (retryCount + 1) + Math.floor(Math.random() * 300)
        await sleep(backoff)
        return callLLM(config, systemPrompt, userMessage, expectJson, textKey, options, retryCount + 1)
      }
    }
    throw error
  }
}

export async function POST(request: NextRequest) {
  let writer: WritableStreamDefaultWriter<Uint8Array> | null = null;

  try {
    const toBoolean = (value: unknown, fallback: boolean) => {
      if (typeof value === 'boolean') return value
      if (typeof value === 'string') {
        const normalized = value.trim().toLowerCase()
        if (normalized === 'true') return true
        if (normalized === 'false') return false
      }
      return fallback
    }

    const body = await request.json()
    const { requirement, options } = body
    const enableOptimization = toBoolean(options?.enableOptimization, true)
    const enableDocGeneration = toBoolean(options?.enableDocGeneration, true)

    if (!requirement || typeof requirement !== 'string') {
      return NextResponse.json(
        { error: '请提供有效的需求描述' },
        { status: 400 }
      )
    }

    // 获取 LLM 配置
    const llmConfig = await db.lLMConfig.findFirst({
      where: { isActive: true }
    })

    if (!llmConfig || !llmConfig.apiKey) {
      return NextResponse.json(
        { error: '请先配置 LLM 服务', needConfig: true },
        { status: 400 }
      )
    }

    // Check cache
    const shouldUseCache = enableOptimization && enableDocGeneration
    const cachedHistory = shouldUseCache
      ? await db.history.findFirst({
          where: {
            question: requirement,
            status: 'success',
            databaseType: llmConfig.databaseType || 'mysql',
            createdAt: {
              gte: new Date(Date.now() - 24 * 60 * 60 * 1000)
            }
          },
          orderBy: { createdAt: 'desc' }
        })
      : null

    if (cachedHistory) {
        // If cached, return immediately (not streaming for simplicity, or simulate stream)
        // To be consistent with frontend, we should probably return JSON directly or stream it.
        // Let's stream the cached result to keep frontend logic unified.
        const cachedResult = JSON.parse(cachedHistory.result)
        
        const stream = new TransformStream()
        const writer = stream.writable.getWriter()
        const encoder = new TextEncoder()

        // Async IIFE to write to stream
        ;(async () => {
            await writer.write(encoder.encode(`event: final_result\ndata: ${JSON.stringify(cachedResult)}\n\n`))
            await writer.close()
        })()

        return new NextResponse(stream.readable, {
            headers: {
                'Content-Type': 'text/event-stream',
                'Cache-Control': 'no-cache',
                'Connection': 'keep-alive',
            }
        })
    }

    const stream = new TransformStream()
    writer = stream.writable.getWriter()
    const encoder = new TextEncoder()

    const sendEvent = async (event: string, data: any) => {
        await writer!.write(encoder.encode(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`))
    }

    const withStageHeartbeat = async <T>(stage: AnalyzeStage, fn: () => Promise<T>): Promise<T> => {
        const timer = setInterval(() => {
            void sendEvent('heartbeat', { stage, timestamp: Date.now() })
        }, HEARTBEAT_INTERVAL_MS)
        try {
            return await fn()
        } finally {
            clearInterval(timer)
        }
    }

    // Start processing in background
    ;(async () => {
        let currentStage: AnalyzeStage = 'optimization'
        try {
            const config = {
                provider: llmConfig.provider,
                apiKey: llmConfig.apiKey,
                baseUrl: llmConfig.baseUrl,
                model: llmConfig.model,
                temperature: llmConfig.temperature,
                maxTokens: llmConfig.maxTokens,
                databaseType: llmConfig.databaseType || 'mysql'
            }
            const startedAt = Date.now()

            // Stage 1: Requirement Optimization
            currentStage = 'optimization'
            let optimizedRequirement = requirement;
            let optimizationResult: any = { optimizedRequirement: requirement };
            
            if (enableOptimization) {
                await sendEvent('stage_start', { stage: 'optimization', message: '正在进行需求扩展与优化...' })
                optimizationResult = await withStageHeartbeat('optimization', () =>
                  callLLM(config, getRequirementOptimizationPrompt(), requirement, false, 'optimizedRequirement', getCallOptions('optimization', startedAt))
                )
                if (!optimizationResult || typeof optimizationResult.optimizedRequirement !== 'string') {
                    throw new Error('需求优化阶段返回数据格式错误')
                }
                await sendEvent('stage_done', { stage: 'optimization', data: optimizationResult })
                optimizedRequirement = optimizationResult.optimizedRequirement;
            } else {
                await sendEvent('stage_start', { stage: 'optimization', message: '需求优化已关闭，跳过该阶段...' })
                await sendEvent('stage_done', { stage: 'optimization', data: optimizationResult })
            }

            // Stage 2: Requirement Analysis
            currentStage = 'analysis'
            await sendEvent('stage_start', { stage: 'analysis', message: '正在提取核心关键点...' })
            const analysisResult = await withStageHeartbeat('analysis', () =>
              callLLM(config, getAnalysisPrompt(), optimizedRequirement, true, undefined, getCallOptions('analysis', startedAt))
            )
            if (!analysisResult || !Array.isArray(analysisResult.keyPoints)) {
                throw new Error('需求分析阶段返回数据格式错误')
            }
            await sendEvent('stage_done', { stage: 'analysis', data: analysisResult })

            // Stage 3: Schema Design
            currentStage = 'design'
            await sendEvent('stage_start', { stage: 'design', message: '正在设计表结构...' })
            const schemaResult = await withStageHeartbeat('design', () =>
              callLLM(config, getSchemaDesignPrompt(config.databaseType, analysisResult.keyPoints), JSON.stringify(analysisResult), true, undefined, getCallOptions('design', startedAt))
            )
             if (!schemaResult || !Array.isArray(schemaResult.tables) || !Array.isArray(schemaResult.relations)) {
                throw new Error('表结构设计阶段返回数据格式错误')
            }
            await sendEvent('stage_done', { stage: 'design', data: schemaResult })

            // Stage 4: SQL Generation
            currentStage = 'sql_generation'
            await sendEvent('stage_start', { stage: 'sql_generation', message: '正在生成 SQL 语句...' })
            const sqlGenerationResult = await withStageHeartbeat('sql_generation', () =>
              callLLM(config, getSqlGenerationPrompt(config.databaseType, schemaResult.tables, schemaResult.relations), JSON.stringify(schemaResult), false, 'sqlStatements', getCallOptions('sql_generation', startedAt))
            )
            if (!sqlGenerationResult || typeof sqlGenerationResult.sqlStatements !== 'string') {
                 throw new Error('SQL生成阶段返回数据格式错误')
            }
            await sendEvent('stage_done', { stage: 'sql_generation', data: sqlGenerationResult })

            // Stage 5: Documentation Generation
            currentStage = 'doc_generation'
            let docGenerationResult: { designDocument: string } = { designDocument: '' }
            
            if (enableDocGeneration) {
                await sendEvent('stage_start', { stage: 'doc_generation', message: '正在生成设计文档...' })
                try {
                    docGenerationResult = await withStageHeartbeat('doc_generation', () =>
                      callLLM(config, getDocumentGenerationPrompt(schemaResult.tables, schemaResult.relations), JSON.stringify(schemaResult), false, 'designDocument', getCallOptions('doc_generation', startedAt))
                    )
                    if (!docGenerationResult || typeof docGenerationResult.designDocument !== 'string') {
                        throw new Error('文档生成阶段返回数据格式错误')
                    }
                    await sendEvent('stage_done', { stage: 'doc_generation', data: docGenerationResult })
                } catch (error) {
                    const message = error instanceof Error ? error.message : '文档生成超时'
                    docGenerationResult = {
                        designDocument: `# 设计文档未完整生成\n\n原因：${message}\n\n当前已返回可用的表结构、ER 图和 SQL 结果。`
                    }
                    await sendEvent('stage_done', { stage: 'doc_generation', data: docGenerationResult, partial: true, error: message })
                }
            } else {
                await sendEvent('stage_start', { stage: 'doc_generation', message: '跳过生成设计文档...' })
                await sendEvent('stage_done', { stage: 'doc_generation', data: docGenerationResult })
            }

            // Combine results
            const finalResult = {
                optimizedRequirement: optimizationResult.optimizedRequirement,
                keyPoints: analysisResult.keyPoints,
                tables: schemaResult.tables,
                relations: schemaResult.relations,
                sqlStatements: sqlGenerationResult.sqlStatements,
                designDocument: docGenerationResult.designDocument,
                databaseType: config.databaseType
            }

            // Save history
            await db.history.create({
                data: {
                    question: requirement,
                    result: JSON.stringify(finalResult),
                    databaseType: config.databaseType,
                    provider: config.provider,
                    model: config.model,
                    status: 'success'
                }
            })

            await sendEvent('final_result', finalResult)
        } catch (error) {
            console.error('Streaming error:', error)
            const errorMessage = error instanceof Error ? error.message : 'Unknown error'
            const errorReason = errorMessage.toLowerCase().includes('failed to parse llm response as json')
              ? 'json_parse_failed'
              : errorMessage.includes('超时')
                ? 'timeout'
                : errorMessage.includes('校验失败')
                  ? 'validation_failed'
                  : 'unknown'
            await sendEvent('error', { message: errorMessage, stage: currentStage, reason: errorReason })
        } finally {
            await writer!.close()
        }
    })()

    return new NextResponse(stream.readable, {
        headers: {
            'Content-Type': 'text/event-stream',
            'Cache-Control': 'no-cache',
            'Connection': 'keep-alive',
        }
    })

  } catch (error) {
    console.error('Request error:', error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Internal Server Error' },
      { status: 500 }
    )
  }
}
