import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'

// Allow for longer timeouts
export const maxDuration = 300; // 5 minutes

// 数据库特定的 SQL 语法指南
const DATABASE_SYNTAX: Record<string, string> = {
  mysql: `
- 使用 MySQL 语法
- 自增主键使用 AUTO_INCREMENT
- 字符串类型使用 VARCHAR(n)，大文本使用 TEXT
- 日期时间使用 DATETIME、TIMESTAMP
- 注释使用 COMMENT 关键字
- 引擎推荐使用 InnoDB: ENGINE=InnoDB
- 字符集推荐 utf8mb4: DEFAULT CHARSET=utf8mb4
- 示例: CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL COMMENT '用户名') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';
`,
  postgresql: `
- 使用 PostgreSQL 语法
- 自增主键使用 SERIAL 或 BIGSERIAL
- 字符串类型使用 VARCHAR(n)，大文本使用 TEXT
- 日期时间使用 TIMESTAMP、TIMESTAMPTZ
- 注释使用 COMMENT ON 语句
- 支持 UUID 类型
- 示例: CREATE TABLE users (id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL);
COMMENT ON TABLE users IS '用户表';
COMMENT ON COLUMN users.name IS '用户名';
`,
  sqlite: `
- 使用 SQLite 语法
- 自增主键使用 INTEGER PRIMARY KEY AUTOINCREMENT
- 字符串类型使用 TEXT（无长度限制）
- 日期时间使用 TEXT 或 DATETIME
- SQLite 不支持 COMMENT 关键字，字段注释放在字段名后用 -- 注释
- 数据类型简化: INTEGER、TEXT、REAL、BLOB
- 示例: CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL -- 用户名);
`,
  sqlserver: `
- 使用 SQL Server (T-SQL) 语法
- 自增主键使用 IDENTITY(1,1)
- 字符串类型使用 NVARCHAR(n)，大文本使用 NVARCHAR(MAX)
- 日期时间使用 DATETIME、DATETIME2
- 注释使用 EXEC sp_addextendedproperty 存储过程
- 支持 UNIQUEIDENTIFIER 类型 (GUID)
- 示例: CREATE TABLE users (id INT IDENTITY(1,1) PRIMARY KEY, name NVARCHAR(100) NOT NULL);
EXEC sp_addextendedproperty 'MS_Description', '用户表', 'SCHEMA', 'dbo', 'TABLE', 'users';
`,
  oracle: `
- 使用 Oracle 语法
- 自增主键使用序列 (SEQUENCE) + 触发器 (TRIGGER) 或 IDENTITY 列 (12c+)
- 字符串类型使用 VARCHAR2(n)，大文本使用 CLOB
- 日期时间使用 DATE、TIMESTAMP
- 注释使用 COMMENT ON 语句
- 表名、字段名推荐使用大写
- 示例: CREATE TABLE USERS (ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, NAME VARCHAR2(100) NOT NULL);
COMMENT ON TABLE USERS IS '用户表';
`,
  mariadb: `
- 使用 MariaDB 语法（与 MySQL 高度兼容）
- 自增主键使用 AUTO_INCREMENT
- 字符串类型使用 VARCHAR(n)，大文本使用 TEXT
- 日期时间使用 DATETIME、TIMESTAMP
- 注释使用 COMMENT 关键字
- 引擎推荐使用 InnoDB: ENGINE=InnoDB
- 字符集推荐 utf8mb4: DEFAULT CHARSET=utf8mb4
- 示例: CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL COMMENT '用户名') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';
`,
  clickhouse: `
- 使用 ClickHouse 语法
- 主键使用 PRIMARY KEY，排序使用 ORDER BY
- 字符串类型使用 String
- 日期时间使用 DateTime、Date
- 注释使用 COMMENT 关键字
- 必须指定 Engine，常用 MergeTree 系列
- 示例: CREATE TABLE users (id UInt64, name String NOT NULL COMMENT '用户名', created_at DateTime DEFAULT now()) ENGINE = MergeTree() ORDER BY id COMMENT '用户表';
`
}

// Stage 1: Requirement Optimization
function getRequirementOptimizationPrompt(): string {
  return `你是一个资深的产品经理兼业务架构师。
用户输入的产品需求往往是口语化、简短或缺乏细节的。你的任务是接收用户的原始需求，结合行业经验，对其进行**脑补、细化和专业化翻译**。
你需要补充潜在的业务逻辑、隐式需求（例如：必要的审计字段、权限控制、状态流转、软删除等），输出一段详细、结构化的标准业务需求描述，以便后续的数据库架构师能根据你的描述设计出健壮的表结构。

【极度重要】：
你只能保留可用于数据库建模的信息：实体、字段、字段约束、主外键关系、索引建议、状态流转、审计字段、业务规则。
必须忽略并剔除 UI/样式/前端实现细节，例如：页面布局、按钮、颜色、间距、字体、动效、组件库、响应式适配、交互文案。
请直接返回详细的业务需求描述，不要任何解释性文字！不要返回 JSON 格式！`
}

// Stage 2: Requirement Analysis
function getAnalysisPrompt(): string {
  return `你是一个资深的业务分析师。
请分析用户的产品需求描述，提取出核心功能关键点。
关键点必须只包含可映射到数据库建模的信息（实体、字段、关系、约束、索引、状态、审计）。
关键点严禁包含 UI、页面、样式、交互动画、组件实现等无关内容。

【极度重要】：
你必须且只能返回一个合法的 JSON 对象！绝对不要输出其他解释性文字！

请严格按照以下JSON格式返回结果，**不要包含任何 markdown 格式，直接返回纯 JSON 字符串**：
{
  "keyPoints": ["关键点1", "关键点2", ...]
}`
}

// Stage 3: Schema Design
function getSchemaDesignPrompt(databaseType: string, keyPoints: string[]): string {
  return `你是一个资深的数据库架构师。
基于以下业务关键点，设计合理的数据库表结构和关系。
业务关键点：
${keyPoints.map(p => `- ${p}`).join('\n')}

【极度重要】：
你必须且只能返回一个合法的 JSON 对象！绝对不要输出其他解释性文字或直接输出 SQL！

请严格按照以下JSON格式返回结果，**不要包含任何 markdown 格式，直接返回纯 JSON 字符串**：
{
  "tables": [
    {
      "name": "表名",
      "comment": "表注释说明",
      "fields": [
        {
          "name": "字段名",
          "type": "字段类型",
          "isPrimary": false,
          "isForeign": false,
          "isNullable": true,
          "comment": "字段注释"
        }
      ]
    }
  ],
  "relations": [
    {
      "fromTable": "源表名",
      "fromField": "源字段名",
      "toTable": "目标表名",
      "toField": "目标字段名",
      "relationType": "1:N 或 1:1 或 N:M"
    }
  ]
}

通用设计原则：
- 每个表必须有主键
- 外键字段命名通常为 {关联表名}_id
- 为关键字段添加索引
- 添加必要的审计字段如 created_at、updated_at
- 关系类型包括：1:1（一对一）、1:N（一对多）、N:M（多对多）
- 对于多对多关系，需要创建中间关联表
- 字段类型请使用通用的描述（如 String, Integer, DateTime），后续会转换为特定数据库语法`
}

// Stage 4: SQL Generation
function getSqlGenerationPrompt(databaseType: string, tables: any[], relations: any[]): string {
  const dbSyntax = DATABASE_SYNTAX[databaseType] || DATABASE_SYNTAX['mysql']
  
  return `你是一个资深的数据库开发工程师。
请根据以下表结构设计，生成符合 ${databaseType.toUpperCase()} 语法的建表语句。

表结构设计：
${JSON.stringify({ tables, relations }, null, 2)}

【极度重要】：
请直接返回完整的 SQL 建表语句，不要任何解释性文字！不要返回 JSON 格式！

数据库特定语法要求 (${databaseType.toUpperCase()})：
${dbSyntax}
`
}

// Stage 5: Documentation Generation
function getDocumentGenerationPrompt(tables: any[], relations: any[]): string {
  return `你是一个资深的技术文档工程师。
请根据以下表结构设计，编写一份标准的数据库设计文档。

表结构设计：
${JSON.stringify({ tables, relations }, null, 2)}

【极度重要】：
请直接返回完整的数据库设计文档（Markdown格式，使用 # 等标题层级，对于数据字典和表关系请使用标准的 Markdown 表格形式展示），不要任何解释性文字！不要返回 JSON 格式！
`
}

const UI_NOISE_TERMS = [
  'ui', 'ux', 'figma', 'css', 'scss', 'sass', 'tailwind', 'bootstrap', 'material ui',
  '页面', '界面', '按钮', '颜色', '配色', '字体', '字号', '圆角', '阴影', '布局', '响应式',
  '动效', '动画', '交互', '弹窗', '抽屉', '导航栏', '卡片', '组件'
]

const BUSINESS_SIGNAL_TERMS = [
  'entity', 'table', 'field', 'column', 'index', 'foreign key', 'primary key', 'constraint',
  'workflow', 'status', 'audit', 'relation', 'schema',
  '实体', '表', '字段', '列', '索引', '主键', '外键', '约束', '状态', '流程', '审计', '关系', '模型'
]

function sanitizeBusinessRequirement(input: string): string {
  const normalized = input.replace(/\r/g, '').trim()
  if (!normalized) return ''

  const sentences = normalized
    .split('\n')
    .flatMap(line => line.split(/(?<=[。！？!?；;])/))
    .map(s => s.trim())
    .filter(Boolean)

  const cleaned = sentences.filter(sentence => {
    const lower = sentence.toLowerCase()
    const hasBusinessSignal = BUSINESS_SIGNAL_TERMS.some(term => lower.includes(term))
    const hasUiNoise = UI_NOISE_TERMS.some(term => lower.includes(term))
    if (hasBusinessSignal) return true
    if (hasUiNoise) return false
    return sentence.length >= 8
  })

  return cleaned.join('\n').trim()
}

function sanitizeKeyPoints(points: string[]): string[] {
  const seen = new Set<string>()
  const cleaned: string[] = []

  for (const point of points) {
    const text = point.trim()
    if (!text) continue
    const lower = text.toLowerCase()
    const hasBusinessSignal = BUSINESS_SIGNAL_TERMS.some(term => lower.includes(term))
    const hasUiNoise = UI_NOISE_TERMS.some(term => lower.includes(term))
    if (hasUiNoise && !hasBusinessSignal) continue
    if (seen.has(text)) continue
    seen.add(text)
    cleaned.push(text)
  }

  return cleaned
}

interface LLMConfig {
  provider: string
  apiKey: string
  baseUrl: string | null
  model: string
  temperature: number
  maxTokens: number
  databaseType: string
}

async function callLLM(
  config: LLMConfig, 
  systemPrompt: string, 
  userMessage: string, 
  expectJson: boolean = true, 
  textKey?: string
): Promise<any> {
  const baseUrl = config.baseUrl || 'https://api.openai.com/v1'
  const url = `${baseUrl}/chat/completions`

  const controller = new AbortController()
  const timeoutId = setTimeout(() => controller.abort(), 120000) // 120s timeout per stage

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${config.apiKey}`
      },
      body: JSON.stringify({
        model: config.model,
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userMessage }
        ],
        temperature: config.temperature,
        max_tokens: config.maxTokens
      }),
      signal: controller.signal
    })

    clearTimeout(timeoutId)

    if (!response.ok) {
      const errorText = await response.text()
      throw new Error(`LLM API 调用失败: ${response.status} - ${errorText}`)
    }

    const text = await response.text()
    let data
    try {
      data = JSON.parse(text)
    } catch (e) {
        // Fallback parsing logic
        console.error('LLM API returned non-JSON response:', text)
        throw new Error(`LLM API returned invalid JSON: ${text.slice(0, 100)}...`)
    }

    const content = data.choices?.[0]?.message?.content
    if (!content) {
       throw new Error('LLM API returned empty content')
    }

    if (!expectJson && textKey) {
        let cleanedContent = content.trim()
        // 去除可能存在的 markdown 代码块包裹
        cleanedContent = cleanedContent.replace(/^```[\w]*\n?/i, '')
                                       .replace(/\n?```$/i, '')
                                       .trim()
        return { [textKey]: cleanedContent }
    }

    // Robust JSON extraction
    let cleanedContent = content.trim()
    const jsonBlockMatch = cleanedContent.match(/```json\s*([\s\S]*?)\s*```/)
    if (jsonBlockMatch) {
      cleanedContent = jsonBlockMatch[1]
    } else {
      const codeBlockMatch = cleanedContent.match(/```\s*([\s\S]*?)\s*```/)
      if (codeBlockMatch) {
        cleanedContent = codeBlockMatch[1]
      }
    }
    
    const firstBrace = cleanedContent.indexOf('{')
    const lastBrace = cleanedContent.lastIndexOf('}')
    if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
      cleanedContent = cleanedContent.substring(firstBrace, lastBrace + 1)
    }

    try {
      return JSON.parse(cleanedContent)
    } catch (e) {
      // 容错处理：如果模型没有返回 JSON 而是直接返回了 SQL 代码（通常包含 CREATE TABLE 或 CREATE DATABASE）
      if (!cleanedContent.includes('{') && (cleanedContent.toUpperCase().includes('CREATE TABLE') || cleanedContent.toUpperCase().includes('CREATE DATABASE'))) {
        return {
          sqlStatements: content.replace(/```sql/gi, '').replace(/```/g, '').replace(/^sql\n/i, '').trim()
        }
      }
      // 容错处理：如果是文档生成阶段返回了纯 Markdown
      if (!cleanedContent.includes('{') && cleanedContent.includes('#')) {
         return {
            designDocument: content.replace(/```markdown/gi, '').replace(/```/g, '').trim()
         }
      }
      console.error('Failed to parse extracted JSON:', cleanedContent)
      throw new Error('Failed to parse LLM response as JSON')
    }

  } catch (error) {
    clearTimeout(timeoutId)
    throw error
  }
}

export async function POST(request: NextRequest) {
  let writer: WritableStreamDefaultWriter<Uint8Array> | null = null;

  try {
    const body = await request.json()
    const { requirement } = body

    if (!requirement || typeof requirement !== 'string') {
      return NextResponse.json(
        { error: '请提供有效的需求描述' },
        { status: 400 }
      )
    }

    // 获取 LLM 配置
    const llmConfig = await db.lLMConfig.findFirst({
      where: { isActive: true }
    })

    if (!llmConfig || !llmConfig.apiKey) {
      return NextResponse.json(
        { error: '请先配置 LLM 服务', needConfig: true },
        { status: 400 }
      )
    }

    // Check cache
    const cachedHistory = await db.history.findFirst({
      where: {
        question: requirement,
        status: 'success',
        databaseType: llmConfig.databaseType || 'mysql',
        createdAt: {
          gte: new Date(Date.now() - 24 * 60 * 60 * 1000)
        }
      },
      orderBy: { createdAt: 'desc' }
    })

    if (cachedHistory) {
        // If cached, return immediately (not streaming for simplicity, or simulate stream)
        // To be consistent with frontend, we should probably return JSON directly or stream it.
        // Let's stream the cached result to keep frontend logic unified.
        const cachedResult = JSON.parse(cachedHistory.result)
        
        const stream = new TransformStream()
        const writer = stream.writable.getWriter()
        const encoder = new TextEncoder()

        // Async IIFE to write to stream
        ;(async () => {
            await writer.write(encoder.encode(`event: final_result\ndata: ${JSON.stringify(cachedResult)}\n\n`))
            await writer.close()
        })()

        return new NextResponse(stream.readable, {
            headers: {
                'Content-Type': 'text/event-stream',
                'Cache-Control': 'no-cache',
                'Connection': 'keep-alive',
            }
        })
    }

    const stream = new TransformStream()
    writer = stream.writable.getWriter()
    const encoder = new TextEncoder()

    const sendEvent = async (event: string, data: any) => {
        await writer!.write(encoder.encode(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`))
    }

    // Start processing in background
    ;(async () => {
        try {
            const config = {
                provider: llmConfig.provider,
                apiKey: llmConfig.apiKey,
                baseUrl: llmConfig.baseUrl,
                model: llmConfig.model,
                temperature: llmConfig.temperature,
                maxTokens: llmConfig.maxTokens,
                databaseType: llmConfig.databaseType || 'mysql'
            }

            // Stage 1: Requirement Optimization
            await sendEvent('stage_start', { stage: 'optimization', message: '正在进行需求扩展与优化...' })
            const optimizationResult = await callLLM(config, getRequirementOptimizationPrompt(), requirement, false, 'optimizedRequirement')
            if (!optimizationResult || typeof optimizationResult.optimizedRequirement !== 'string') {
                throw new Error('需求优化阶段返回数据格式错误')
            }
            const sanitizedRequirement = sanitizeBusinessRequirement(optimizationResult.optimizedRequirement)
            if (!sanitizedRequirement) {
                throw new Error('需求优化阶段未提取到可用于建表的业务信息')
            }
            await sendEvent('stage_done', { stage: 'optimization', data: { optimizedRequirement: sanitizedRequirement } })

            // Stage 2: Requirement Analysis
            await sendEvent('stage_start', { stage: 'analysis', message: '正在提取核心关键点...' })
            const analysisResult = await callLLM(config, getAnalysisPrompt(), sanitizedRequirement, true)
            if (!analysisResult || !Array.isArray(analysisResult.keyPoints)) {
                throw new Error('需求分析阶段返回数据格式错误')
            }
            const sanitizedKeyPoints = sanitizeKeyPoints(analysisResult.keyPoints)
            if (sanitizedKeyPoints.length === 0) {
                throw new Error('需求分析阶段未提取到可用于建表的关键点')
            }
            const normalizedAnalysisResult = { ...analysisResult, keyPoints: sanitizedKeyPoints }
            await sendEvent('stage_done', { stage: 'analysis', data: normalizedAnalysisResult })

            // Stage 3: Schema Design
            await sendEvent('stage_start', { stage: 'design', message: '正在设计表结构...' })
            const schemaResult = await callLLM(config, getSchemaDesignPrompt(config.databaseType, sanitizedKeyPoints), JSON.stringify(normalizedAnalysisResult), true)
             if (!schemaResult || !Array.isArray(schemaResult.tables) || !Array.isArray(schemaResult.relations)) {
                throw new Error('表结构设计阶段返回数据格式错误')
            }
            await sendEvent('stage_done', { stage: 'design', data: schemaResult })

            // Stage 4: SQL Generation
            await sendEvent('stage_start', { stage: 'sql_generation', message: '正在生成 SQL 语句...' })
            const sqlGenerationResult = await callLLM(config, getSqlGenerationPrompt(config.databaseType, schemaResult.tables, schemaResult.relations), JSON.stringify(schemaResult), false, 'sqlStatements')
            if (!sqlGenerationResult || typeof sqlGenerationResult.sqlStatements !== 'string') {
                 throw new Error('SQL生成阶段返回数据格式错误')
            }
            await sendEvent('stage_done', { stage: 'sql_generation', data: sqlGenerationResult })

            // Stage 5: Documentation Generation
            await sendEvent('stage_start', { stage: 'doc_generation', message: '正在生成设计文档...' })
            const docGenerationResult = await callLLM(config, getDocumentGenerationPrompt(schemaResult.tables, schemaResult.relations), JSON.stringify(schemaResult), false, 'designDocument')
            if (!docGenerationResult || typeof docGenerationResult.designDocument !== 'string') {
                 throw new Error('文档生成阶段返回数据格式错误')
            }
            await sendEvent('stage_done', { stage: 'doc_generation', data: docGenerationResult })

            // Combine results
            const finalResult = {
                optimizedRequirement: sanitizedRequirement,
                keyPoints: sanitizedKeyPoints,
                tables: schemaResult.tables,
                relations: schemaResult.relations,
                sqlStatements: sqlGenerationResult.sqlStatements,
                designDocument: docGenerationResult.designDocument,
                databaseType: config.databaseType
            }

            // Save history
            await db.history.create({
                data: {
                    question: requirement,
                    result: JSON.stringify(finalResult),
                    databaseType: config.databaseType,
                    provider: config.provider,
                    model: config.model,
                    status: 'success'
                }
            })

            await sendEvent('final_result', finalResult)
        } catch (error) {
            console.error('Streaming error:', error)
            const errorMessage = error instanceof Error ? error.message : 'Unknown error'
            await sendEvent('error', { message: errorMessage })
        } finally {
            await writer!.close()
        }
    })()

    return new NextResponse(stream.readable, {
        headers: {
            'Content-Type': 'text/event-stream',
            'Cache-Control': 'no-cache',
            'Connection': 'keep-alive',
        }
    })

  } catch (error) {
    console.error('Request error:', error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Internal Server Error' },
      { status: 500 }
    )
  }
}
